import logging
from pathlib import Path
from typing import List, Dict, Any
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
import os

# --- Logging Configuration ---
logger = logging.getLogger("RetrieverTool")
logging.basicConfig(level=logging.INFO)
os.environ['ANONYMIZED_TELEMETRY'] = 'False'
def retriever_tool(queries: List[str]) -> Dict[str, Any]:
    """
    Executes the retrieval strategy by querying a persistent ChromaDB vector store.
    
    Args:
        queries (List[str]): A list of sub-queries generated by the Planner Agent.

    Returns:
        Dict[str, Any]: A dictionary containing the concatenated retrieved text.
    """
    logger.info(f"Retriever tool triggered with {len(queries)} queries.")
    
    try:
        # 1. Path Management
        # use .resolve() to ensure paths are absolute and work across different environments
        current_dir = Path(__file__).parent.resolve()
        # Adjusted path logic to find your 'vectorstore/chroma_db' folder
        vector_db_path = current_dir.parent.parent / "vectorstore" / "chroma_db"
        persist_dir = str(vector_db_path)

        if not vector_db_path.exists():
            logger.error(f"Vector database path not found: {persist_dir}")
            return {"retriever_content": "Error: Vector database directory missing."}

        # 2. Model Initialization
        logger.info("Loading embedding model...")
        embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

        # 3. Connection to ChromaDB
        logger.info(f"Connecting to ChromaDB at: {persist_dir}")
        vectordb = Chroma(
            persist_directory=persist_dir,
            embedding_function=embedding_model
        )

        all_retrieved_docs = []

        # 4. Search Loop
        for query in queries:
            try:
                logger.info(f"Running similarity search for: '{query}'")
                # Removed the undefined 'filters' variable that caused the previous error
                docs = vectordb.similarity_search(query=query, k=3)
                all_retrieved_docs.extend(docs)
            except Exception as e:
                logger.warning(f"Search failed for query '{query}': {str(e)}")
                continue

        # 5. Result Processing
        if not all_retrieved_docs:
            logger.warning("No documents were retrieved from the database.")
            return {"retriever_content": "No relevant documents found in the database."}

        # Use a set to remove duplicate documents if sub-queries overlap
        unique_contents = list(dict.fromkeys([doc.page_content for doc in all_retrieved_docs]))
        combined_content = "\n\n---\n\n".join(unique_contents)

        logger.info(f"Successfully retrieved {len(unique_contents)} unique document segments.")
        
        return {
            "retriever_content": combined_content
        }

    except Exception as e:
        logger.error(f"Critical error in retriever_tool: {str(e)}", exc_info=True)
        return {"retriever_content": f"An internal error occurred during retrieval: {str(e)}"}